# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandapps', '0002_video_first'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('pseudo', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
