# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandapps', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='sujet',
            field=models.CharField(default='', max_length=500),
        ),
    ]
