# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandapps', '0005_auto_20161220_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
